name: Unit Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests

    env:
      FLAGS: "-ggdb -O0 -fsanitize=address -fsanitize=leak -fsanitize=undefined"

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Get build dependencies
        run: |
          sudo apt-get build-dep -qq -y -Ppkg.ngcp-rtpengine.nobcg729 .

      - name: Run unit tests with sanitizers enabled
        run: |
          CFLAGS="$FLAGS" LDFLAGS="$FLAGS" ASAN_OPTIONS=verify_asan_link_order=0 UBSAN_OPTIONS=print_stacktrace=1 G_SLICE=always-malloc make check
